# Deprecated: is to be included in the default 'application.yml', and the logfile in the 'local' and 'docker' profile
# Will be removed once discovery and admin services are dockerized
logging:
  level:
    org.springframework: DEBUG
    nl.danman: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3
  file:
    name: D:\\var\\log\\service-universe\\${spring.application.name}.log