management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      group:
        custom:
          include:
            - diskSpace
            - ping
          show-components: always
          show-details: always
    env:
      enabled: true
      show-values: always
    configprops:
      show-values: always

---

logging:
  level:
    org.springframework: INFO
    nl.danman: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3

---

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    service-url:
      defaultZone: http://localhost:8910/eureka
    registry-fetch-interval-seconds: 5