
# Deprecated: is to be included in the default 'application.yml'
# Will be removed once discovery and admin services are dockerized
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      enabled: true
      show-values: always