logging:
  file:
    name: /service-universe/log/${spring.application.name}.log

---

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    service-url:
      defaultZone: http://su-discovery-service:8910/eureka
    registry-fetch-interval-seconds: 5