logging:
  level:
    org.springframework: DEBUG
    nl.danman: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3
  file:
    name: D:\\var\\log\\service-universe\\${spring.application.name}.log